### PR TITLE
Fixed issue #14 "Move the content header to middle"

### PR DESCRIPTION
**Pull request by Symphoria**
Please ignore my first commit. I will create a separate issue for the image bug in question.html and then request a PR. This PR only resolves issue#14.

### CODE REVIEW

**Comment by gauthamzz** [comment]
Post a screenshot please

**Comment by Symphoria** [comment]
Ok, will look for better solution for issue #21. For issue #14 do I create a separate PR after reverting the changes I did in issue #21?

**Comment by gauthamzz** [comment]
You need to create separate PR for each issue you solve.

**Comment by Symphoria** [comment]
Ok, I will close this PR and create a new PR only for issue #14

**Comment by gauthamzz** [comment]
One more thing . Your PR should have only the files you changed in it . Do git add in that way

**Comment by Symphoria** [comment]
Ok

**Comment by Symphoria** [comment]
Screenshot of register page

screenshot_register

**Pull request closed without merging**
